config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('about/', include('pages.urls', namespace='pages')),
    path('admin/', admin.site.urls),
]

config/pages/urls.py
from django.urls import path
from .views import AboutPageView, HomePageView

app_name = 'pages'

urlpatterns = [
     path('', HomePageView.as_view(), name='home'),
     path('about/',AboutPageView.as_view(), name = 'about')
]

config/pages/models.py
from django.db import models

# Create your models here.

config/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name='pages/home.html'

class AboutPageView(TemplateView):
    template_name='pages/about.html'

config/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
  <head> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title>
        {%block title%}  
        {%endblock%} 
    </title> 
  </head>
  <body>       
      {% include "includes/header.html" %}
    {% block content %}
    <main>
      Информация на главной странице
    </main>
    {% endblock %}
    <footer>
      {% include "includes/footer.html" %} 
    </footer>
  </body>
</html> 

config/templates/includes/header.html
<header>
    <a href="{% url 'pages:home' %}">Home</a> |
    <a href="{% url 'pages:about' %}">About</a>
</header>

config/templates/pages/about.html
{% extends 'base.html' %}
{% block titile %}
  Об авторе
{% endblock %}
{% block content %}
  <h1>Страница об авторе</h1>
{% endblock %}

config/templates/pages/home.html
{% extends 'base.html' %}
{% block titile %}
  <title>Домашняя страница</title>
{% endblock %}
{% block content %}
  <h1>Домашняя страница</h1>
{% endblock %}